global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: online-voting-otel-collector
    static_configs:
      - targets:
          - online-voting-otel-collector:8889